
/*
try {
console.log(naotem);
}catch (err) {
console.log('nao tem nada');
console.log(err);
}
*/

try {
 // é executa quando não há erros 
} catch (e) { 
// é executada quando há erros 
} finally { 
    //sempre é executado 
}
